export const annualProduce = [
  [
    { name: 'Apples', type: 'fruit' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Brussels Sprouts', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Celeriac', type: 'vegetable' },
    { name: 'Celery', type: 'vegetable' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Jerusalem Artichokes', type: 'vegetable' },
    { name: 'Kale', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Mushrooms', type: 'vegetable' },
    { name: 'Onions', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Pears', type: 'fruit' },
    { name: 'Red Cabbage', type: 'vegetable' },
    { name: 'Savoy Cabbage', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Squash', type: 'vegetable' },
    { name: 'Swedes', type: 'vegetable' },
    { name: 'Turnips', type: 'vegetable' },
    { name: 'White Cabbage', type: 'vegetable' },
  ],

  [
    { name: 'Apples', type: 'fruit' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Brussels Sprouts', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Celeriac', type: 'vegetable' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Jerusalem Artichokes', type: 'vegetable' },
    { name: 'Kale', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Mushrooms', type: 'vegetable' },
    { name: 'Onions', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Pears', type: 'fruit' },
    { name: 'Purple Sprouting Broccoli', type: 'vegetable' },
    { name: 'Red Cabbage', type: 'vegetable' },
    { name: 'Salsify', type: 'vegetable' },
    { name: 'Savoy Cabbage', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Squash', type: 'vegetable' },
    { name: 'Swedes', type: 'vegetable' },
    { name: 'White Cabbage', type: 'vegetable' },
  ],

  [
    { name: 'Artichoke', type: 'vegetable' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Purple Sprouting Broccoli', type: 'vegetable' },
    { name: 'Rhubarb', type: 'vegetable' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Sorrel', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
  ],

  [
    { name: 'Artichoke', type: 'vegetable' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'New Potatoes', type: 'vegetable' },
    { name: 'Kale', type: 'vegetable' },
    { name: 'Mushrooms', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Rhubarb', type: 'vegetable' },
    { name: 'Rocket', type: 'vegetable' },
    { name: 'Sorrel', type: 'vegetable' },
    { name: 'Spinach', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
  ],

  [
    { name: 'Artichoke', type: 'vegetable' },
    { name: 'Asparagus', type: 'vegetable' },
    { name: 'Aubergine', type: 'vegetable' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Chillies', type: 'vegetable' },
    { name: 'Elderflowers', type: 'vegetable' },
    { name: 'Lettuce', type: 'vegetable' },
    { name: 'Marrow', type: 'vegetable' },
    { name: 'New Potatoes', type: 'vegetable' },
    { name: 'Peas', type: 'vegetable' },
    { name: 'Peppers', type: 'vegetable' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Rhubarb', type: 'vegetable' },
    { name: 'Rocket', type: 'vegetable' },
    { name: 'Samphire', type: 'vegetable' },
    { name: 'Sorrel', type: 'vegetable' },
    { name: 'Spinach', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Strawberries', type: 'fruit' },
    { name: 'Sweetheart Cabbage', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
  ],

  [
    { name: 'Asparagus', type: 'vegetable' },
    { name: 'Aubergine', type: 'vegetable' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Blackcurrants', type: 'fruit' },
    { name: 'Broad Beans', type: 'vegetable' },
    { name: 'Broccoli', type: 'vegetable' },
    { name: 'Cauliflower', type: 'vegetable' },
    { name: 'Cherries', type: 'fruit' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Chillies', type: 'vegetable' },
    { name: 'Courgettes', type: 'vegetable' },
    { name: 'Cucumber', type: 'vegetable' },
    { name: 'Elderflowers', type: 'flower' },
    { name: 'Gooseberries', type: 'fruit' },
    { name: 'Lettuce', type: 'vegetable' },
    { name: 'Marrow', type: 'vegetable' },
    { name: 'New Potatoes', type: 'vegetable' },
    { name: 'Peas', type: 'vegetable' },
    { name: 'Peppers', type: 'vegetable' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Raspberries', type: 'fruit' },
    { name: 'Redcurrants', type: 'fruit' },
    { name: 'Rhubarb', type: 'vegetable' },
    { name: 'Rocket', type: 'vegetable' },
    { name: 'Runner Beans', type: 'vegetable' },
    { name: 'Samphire', type: 'vegetable' },
    { name: 'Sorrel', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Strawberries', type: 'fruit' },
    { name: 'Summer Squash', type: 'vegetable' },
    { name: 'Sweetheart Cabbage', type: 'vegetable' },
    { name: 'Swiss Chard', type: 'vegetable' },
    { name: 'Tayberries', type: 'fruit' },
    { name: 'Turnips', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
  ],

  [
    { name: 'Aubergine', type: 'vegetable' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Blackberries', type: 'fruit' },
    { name: 'Blackcurrants', type: 'fruit' },
    { name: 'Blueberries', type: 'fruit' },
    { name: 'Broad Beans', type: 'vegetable' },
    { name: 'Broccoli', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Cauliflower', type: 'vegetable' },
    { name: 'Cherries', type: 'fruit' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Chillies', type: 'vegetable' },
    { name: 'Courgettes', type: 'vegetable' },
    { name: 'Cucumber', type: 'vegetable' },
    { name: 'Gooseberries', type: 'fruit' },
    { name: 'Greengages', type: 'fruit' },
    { name: 'Fennel', type: 'vegetable' },
    { name: 'French Beans', type: 'vegetable' },
    { name: 'Garlic', type: 'vegetable' },
    { name: 'Kohlrabi', type: 'vegetable' },
    { name: 'Loganberries', type: 'fruit' },
    { name: 'New Potatoes', type: 'vegetable' },
    { name: 'Onions', type: 'vegetable' },
    { name: 'Peas', type: 'vegetable' },
    { name: 'Potatoes', type: 'vegetable' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Raspberries', type: 'fruit' },
    { name: 'Redcurrants', type: 'fruit' },
    { name: 'Rhubarb', type: 'vegetable' },
    { name: 'Rocket', type: 'vegetable' },
    { name: 'Runner Beans', type: 'vegetable' },
    { name: 'Samphire', type: 'vegetable' },
    { name: 'Sorrel', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Strawberries', type: 'fruit' },
    { name: 'Summer Squash', type: 'vegetable' },
    { name: 'Sweetheart Cabbage', type: 'vegetable' },
    { name: 'Swiss Chard', type: 'vegetable' },
    { name: 'Tomatoes', type: 'fruit' },
    { name: 'Turnips', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
  ],

  [
    { name: 'Aubergine', type: 'vegetable' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Blackberries', type: 'fruit' },
    { name: 'Blackcurrants', type: 'fruit' },
    { name: 'Broad Beans', type: 'vegetable' },
    { name: 'Broccoli', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Cauliflower', type: 'vegetable' },
    { name: 'Cherries', type: 'fruit' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Chillies', type: 'vegetable' },
    { name: 'Courgettes', type: 'vegetable' },
    { name: 'Cucumber', type: 'vegetable' },
    { name: 'Damsons', type: 'fruit' },
    { name: 'Fennel', type: 'vegetable' },
    { name: 'French Beans', type: 'vegetable' },
    { name: 'Garlic', type: 'vegetable' },
    { name: 'Greengages', type: 'fruit' },
    { name: 'Kohlrabi', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Lettuce', type: 'vegetable' },
    { name: 'Loganberries', type: 'fruit' },
    { name: 'Mangetout', type: 'vegetable' },
    { name: 'Marrow', type: 'vegetable' },
    { name: 'Mushrooms', type: 'fungus' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Peas', type: 'vegetable' },
    { name: 'Peppers', type: 'vegetable' },
    { name: 'Potatoes', type: 'vegetable' },
    { name: 'Plums', type: 'fruit' },
    { name: 'Pumpkin', type: 'vegetable' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Raspberries', type: 'fruit' },
    { name: 'Redcurrants', type: 'fruit' },
    { name: 'Rhubarb', type: 'vegetable' },
    { name: 'Rocket', type: 'vegetable' },
    { name: 'Runner Beans', type: 'vegetable' },
    { name: 'Samphire', type: 'vegetable' },
    { name: 'Sorrel', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Strawberries', type: 'fruit' },
    { name: 'Summer Squash', type: 'vegetable' },
    { name: 'Sweetcorn', type: 'vegetable' },
    { name: 'Sweetheart Cabbage', type: 'vegetable' },
    { name: 'Swiss Chard', type: 'vegetable' },
    { name: 'Tomatoes', type: 'fruit' },
    { name: 'Watercress', type: 'vegetable' },
    { name: 'White Cabbage', type: 'vegetable' },
  ],

  [
    { name: 'Aubergine', type: 'vegetable' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Blackberries', type: 'fruit' },
    { name: 'Broccoli', type: 'vegetable' },
    { name: 'Brussels Sprouts', type: 'vegetable' },
    { name: 'Butternut Squash', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Cauliflower', type: 'vegetable' },
    { name: 'Celery', type: 'vegetable' },
    { name: 'Courgettes', type: 'vegetable' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Chillies', type: 'vegetable' },
    { name: 'Cucumber', type: 'vegetable' },
    { name: 'Damsons', type: 'fruit' },
    { name: 'Garlic', type: 'vegetable' },
    { name: 'Kale', type: 'vegetable' },
    { name: 'Kohlrabi', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Lettuce', type: 'vegetable' },
    { name: 'Mangetout', type: 'vegetable' },
    { name: 'Marrow', type: 'vegetable' },
    { name: 'Onions', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Pears', type: 'fruit' },
    { name: 'Peas', type: 'vegetable' },
    { name: 'Peppers', type: 'vegetable' },
    { name: 'Plums', type: 'fruit' },
    { name: 'Potatoes', type: 'vegetable' },
    { name: 'Pumpkin', type: 'vegetable' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Raspberries', type: 'fruit' },
    { name: 'Red Cabbage', type: 'vegetable' },
    { name: 'Rhubarb', type: 'vegetable' },
    { name: 'Rocket', type: 'vegetable' },
    { name: 'Runner Beans', type: 'vegetable' },
    { name: 'Samphire', type: 'vegetable' },
    { name: 'Sorrel', type: 'vegetable' },
    { name: 'Spinach', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Strawberries', type: 'fruit' },
    { name: 'Summer Squash', type: 'vegetable' },
    { name: 'Sweetcorn', type: 'vegetable' },
    { name: 'Sweetheart Cabbage', type: 'vegetable' },
    { name: 'Swiss Chard', type: 'vegetable' },
    { name: 'Tomatoes', type: 'fruit' },
    { name: 'Turnips', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
    { name: 'Wild Mushrooms', type: 'fungus' },
    { name: 'White Cabbage', type: 'vegetable' },
  ],

  [
    { name: 'Apples', type: 'fruit' },
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Blackberries', type: 'fruit' },
    { name: 'Broccoli', type: 'vegetable' },
    { name: 'Brussels Sprouts', type: 'vegetable' },
    { name: 'Butternut Squash', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Cauliflower', type: 'vegetable' },
    { name: 'Celeriac', type: 'vegetable' },
    { name: 'Celery', type: 'vegetable' },
    { name: 'Chestnuts', type: 'nut' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Chillies', type: 'vegetable' },
    { name: 'Courgette', type: 'vegetable' },
    { name: 'Cucumber', type: 'vegetable' },
    { name: 'Elderberries', type: 'fruit' },
    { name: 'Kale', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Lettuce', type: 'vegetable' },
    { name: 'Onions', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Pears', type: 'fruit' },
    { name: 'Peas', type: 'vegetable' },
    { name: 'Potatoes', type: 'vegetable' },
    { name: 'Aubergine', type: 'vegetable' },
    { name: 'Pumpkin', type: 'vegetable' },
    { name: 'Quince', type: 'fruit' },
    { name: 'Radishes', type: 'vegetable' },
    { name: 'Red Cabbage', type: 'vegetable' },
    { name: 'Rocket', type: 'vegetable' },
    { name: 'Runner Beans', type: 'vegetable' },
    { name: 'Salsify', type: 'vegetable' },
    { name: 'Savoy Cabbage', type: 'vegetable' },
    { name: 'Spinach', type: 'vegetable' },
    { name: 'Spring Greens', type: 'vegetable' },
    { name: 'Spring Onions', type: 'vegetable' },
    { name: 'Summer Squash', type: 'vegetable' },
    { name: 'Swede', type: 'vegetable' },
    { name: 'Sweetcorn', type: 'vegetable' },
    { name: 'Sweetheart Cabbage', type: 'vegetable' },
    { name: 'Swiss Chard', type: 'vegetable' },
    { name: 'Tomatoes', type: 'fruit' },
    { name: 'Turnips', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
    { name: 'Wild Mushrooms', type: 'fungus' },
    { name: 'Winter Squash', type: 'vegetable' },
    { name: 'White Cabbage', type: 'vegetable' },
    { name: 'Marrow', type: 'vegetable' },
  ],

  [
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Brussels Sprouts', type: 'vegetable' },
    { name: 'Butternut Squash', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Cauliflower', type: 'vegetable' },
    { name: 'Celeriac', type: 'vegetable' },
    { name: 'Celery', type: 'vegetable' },
    { name: 'Chestnuts', type: 'nut' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Cranberries', type: 'fruit' },
    { name: 'Elderberries', type: 'fruit' },
    { name: 'Jerusalem Artichokes', type: 'vegetable' },
    { name: 'Kale', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Onions', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Pears', type: 'fruit' },
    { name: 'Potatoes', type: 'vegetable' },
    { name: 'Pumpkin', type: 'vegetable' },
    { name: 'Quince', type: 'fruit' },
    { name: 'Red Cabbage', type: 'vegetable' },
    { name: 'Salsify', type: 'vegetable' },
    { name: 'Savoy Cabbage', type: 'vegetable' },
    { name: 'Swede', type: 'vegetable' },
    { name: 'Swiss Chard', type: 'vegetable' },
    { name: 'Turnips', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
    { name: 'Wild Mushrooms', type: 'fungus' },
    { name: 'Winter Squash', type: 'vegetable' },
    { name: 'White Cabbage', type: 'vegetable' },
    { name: 'Apples', type: 'fruit' },
  ],

  [
    { name: 'Beetroot', type: 'vegetable' },
    { name: 'Brussels Sprouts', type: 'vegetable' },
    { name: 'Carrots', type: 'vegetable' },
    { name: 'Celeriac', type: 'vegetable' },
    { name: 'Celery', type: 'vegetable' },
    { name: 'Chestnuts', type: 'nut' },
    { name: 'Chicory', type: 'vegetable' },
    { name: 'Cranberries', type: 'fruit' },
    { name: 'Jerusalem Artichokes', type: 'vegetable' },
    { name: 'Kale', type: 'vegetable' },
    { name: 'Leeks', type: 'vegetable' },
    { name: 'Mushrooms', type: 'fungus' },
    { name: 'Onions', type: 'vegetable' },
    { name: 'Parsnips', type: 'vegetable' },
    { name: 'Pears', type: 'fruit' },
    { name: 'Potatoes', type: 'vegetable' },
    { name: 'Pumpkin', type: 'vegetable' },
    { name: 'Quince', type: 'fruit' },
    { name: 'Red Cabbage', type: 'vegetable' },
    { name: 'Salsify', type: 'vegetable' },
    { name: 'Savoy Cabbage', type: 'vegetable' },
    { name: 'Swede', type: 'vegetable' },
    { name: 'Swiss Chard', type: 'vegetable' },
    { name: 'Turnips', type: 'vegetable' },
    { name: 'Watercress', type: 'vegetable' },
    { name: 'Winter Squash', type: 'vegetable' },
    { name: 'White Cabbage', type: 'vegetable' },
  ],
];
